version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '40080:80'   # Public HTTP Port
      - '40443:443'  # Public HTTPS Port
      - '40081:81'   # Admin Web Port
    volumes:
      - /mnt/MainDrive/Config/nginx/data:/data
      - /mnt/MainDrive/Config/nginx/letsencrypt:/etc/letsencrypt
